/**
 */
package clicker_Generator.provider;

import clicker_Generator.util.Clicker_GeneratorAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Clicker_GeneratorItemProviderAdapterFactory extends Clicker_GeneratorAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Clicker_GeneratorItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.game} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected gameItemProvider gameItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.game}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter creategameAdapter() {
		if (gameItemProvider == null) {
			gameItemProvider = new gameItemProvider(this);
		}

		return gameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.resource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected resourceItemProvider resourceItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.resource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createresourceAdapter() {
		if (resourceItemProvider == null) {
			resourceItemProvider = new resourceItemProvider(this);
		}

		return resourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.generator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected generatorItemProvider generatorItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.generator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter creategeneratorAdapter() {
		if (generatorItemProvider == null) {
			generatorItemProvider = new generatorItemProvider(this);
		}

		return generatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.upgrade} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected upgradeItemProvider upgradeItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.upgrade}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createupgradeAdapter() {
		if (upgradeItemProvider == null) {
			upgradeItemProvider = new upgradeItemProvider(this);
		}

		return upgradeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.multiplyRateEffect} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected multiplyRateEffectItemProvider multiplyRateEffectItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.multiplyRateEffect}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createmultiplyRateEffectAdapter() {
		if (multiplyRateEffectItemProvider == null) {
			multiplyRateEffectItemProvider = new multiplyRateEffectItemProvider(this);
		}

		return multiplyRateEffectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.reduceCostEffect} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected reduceCostEffectItemProvider reduceCostEffectItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.reduceCostEffect}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createreduceCostEffectAdapter() {
		if (reduceCostEffectItemProvider == null) {
			reduceCostEffectItemProvider = new reduceCostEffectItemProvider(this);
		}

		return reduceCostEffectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.unlockGeneratorEffect} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected unlockGeneratorEffectItemProvider unlockGeneratorEffectItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.unlockGeneratorEffect}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createunlockGeneratorEffectAdapter() {
		if (unlockGeneratorEffectItemProvider == null) {
			unlockGeneratorEffectItemProvider = new unlockGeneratorEffectItemProvider(this);
		}

		return unlockGeneratorEffectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.achievement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected achievementItemProvider achievementItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.achievement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createachievementAdapter() {
		if (achievementItemProvider == null) {
			achievementItemProvider = new achievementItemProvider(this);
		}

		return achievementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.comparison} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected comparisonItemProvider comparisonItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.comparison}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createcomparisonAdapter() {
		if (comparisonItemProvider == null) {
			comparisonItemProvider = new comparisonItemProvider(this);
		}

		return comparisonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.binaryExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected binaryExpressionItemProvider binaryExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.binaryExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createbinaryExpressionAdapter() {
		if (binaryExpressionItemProvider == null) {
			binaryExpressionItemProvider = new binaryExpressionItemProvider(this);
		}

		return binaryExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link clicker_Generator.event} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected eventItemProvider eventItemProvider;

	/**
	 * This creates an adapter for a {@link clicker_Generator.event}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createeventAdapter() {
		if (eventItemProvider == null) {
			eventItemProvider = new eventItemProvider(this);
		}

		return eventItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (gameItemProvider != null)
			gameItemProvider.dispose();
		if (resourceItemProvider != null)
			resourceItemProvider.dispose();
		if (generatorItemProvider != null)
			generatorItemProvider.dispose();
		if (upgradeItemProvider != null)
			upgradeItemProvider.dispose();
		if (multiplyRateEffectItemProvider != null)
			multiplyRateEffectItemProvider.dispose();
		if (reduceCostEffectItemProvider != null)
			reduceCostEffectItemProvider.dispose();
		if (unlockGeneratorEffectItemProvider != null)
			unlockGeneratorEffectItemProvider.dispose();
		if (achievementItemProvider != null)
			achievementItemProvider.dispose();
		if (comparisonItemProvider != null)
			comparisonItemProvider.dispose();
		if (binaryExpressionItemProvider != null)
			binaryExpressionItemProvider.dispose();
		if (eventItemProvider != null)
			eventItemProvider.dispose();
	}

}
